// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Qv4SVL-Wh5-9_IuaccsHXO2osD5alTw',
    appId: '1:96096356348:web:2199f9005a44769a379479',
    messagingSenderId: '96096356348',
    projectId: 'jeson-project',
    authDomain: 'jeson-project.firebaseapp.com',
    databaseURL: 'https://jeson-project-default-rtdb.firebaseio.com',
    storageBucket: 'jeson-project.appspot.com',
    measurementId: 'G-V35YV34FZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsBhxHaz0-X6bi3tXVlCdh3oHyolIB3-c',
    appId: '1:96096356348:android:89d8e5e0a534f469379479',
    messagingSenderId: '96096356348',
    projectId: 'jeson-project',
    databaseURL: 'https://jeson-project-default-rtdb.firebaseio.com',
    storageBucket: 'jeson-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY2bTOJKRoDp4Y8DQNo9uW1apvasLdirg',
    appId: '1:96096356348:ios:75d964790d3793fb379479',
    messagingSenderId: '96096356348',
    projectId: 'jeson-project',
    databaseURL: 'https://jeson-project-default-rtdb.firebaseio.com',
    storageBucket: 'jeson-project.appspot.com',
    iosClientId: '96096356348-ug5ikbkj4t26g6k1c6jsqtgod1b1b4k0.apps.googleusercontent.com',
    iosBundleId: 'com.jeson.app.jesonFlutterApp',
  );
}
