// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0yTdgrPKGTdlOk2J8U6rzUEJsI5UYrVk',
    appId: '1:827106228620:web:73070ed0a5d5aaa64f7ea9',
    messagingSenderId: '827106228620',
    projectId: 'jeson-app',
    authDomain: 'jeson-app.firebaseapp.com',
    databaseURL: 'https://jeson-app-default-rtdb.firebaseio.com',
    storageBucket: 'jeson-app.appspot.com',
    measurementId: 'G-P5RQ751B13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIn_HW9OZpAruKfViRP9ddfwM6x3wA6NA',
    appId: '1:827106228620:android:6327da4e2af33ddd4f7ea9',
    messagingSenderId: '827106228620',
    projectId: 'jeson-app',
    databaseURL: 'https://jeson-app-default-rtdb.firebaseio.com',
    storageBucket: 'jeson-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6O9z2At-7v4SO7lPFd9bJDQbeR8S-IGg',
    appId: '1:827106228620:ios:0499ff49b1b48c654f7ea9',
    messagingSenderId: '827106228620',
    projectId: 'jeson-app',
    databaseURL: 'https://jeson-app-default-rtdb.firebaseio.com',
    storageBucket: 'jeson-app.appspot.com',
    iosClientId: '827106228620-6ct4fe2tdeg2t4nnp1ggaa8651grcliq.apps.googleusercontent.com',
    iosBundleId: 'com.jeson.app.jesonFlutterApp',
  );
}
